# Generated by Django 4.2.7 on 2023-11-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='comment',
            new_name='command',
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fakulteti'),
        ),
    ]
