# Generated by Django 4.2.7 on 2023-11-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_comment_student_command_student_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hemis_id',
            field=models.BigIntegerField(editable=False, unique=True, verbose_name='HEMIS ID'),
        ),
    ]
