# Generated by Django 4.2.7 on 2023-11-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_hemis_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('1-kurs', '1-kurs'), ('2-kurs', '2-kurs'), ('3-kurs', '3-kurs'), ('4-kurs', '4-kurs'), ('5-kurs', '5-kurs')], max_length=255, verbose_name='Kursi'),
        ),
    ]
