# Generated by Django 4.2.7 on 2023-12-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiyasi'),
        ),
    ]
