# Generated by Django 4.2.7 on 2024-09-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_student_phone_alter_telegramuser_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='group',
            new_name='stgroup',
        ),
        migrations.AlterField(
            model_name='student',
            name='is_graduated',
            field=models.CharField(verbose_name='Bitirganmi'),
        ),
    ]
