# Generated by Django 4.2.7 on 2024-09-24 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_group_student_stgroup_remove_student_jshshir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Tuliq ismi')),
                ('passport', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pasport seriyasi')),
                ('jshshir', models.CharField(blank=True, max_length=255, null=True, verbose_name='jshshir')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lavozimi')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name="Bo'limi")),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('dob', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sanasi")),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='is_returned',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Qaytarildimi'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_subscribed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Obuna'),
        ),
        migrations.CreateModel(
            name='IssuedBookEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(auto_now_add=True, verbose_name='Berilgan sana')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='Qaytarilgan sana')),
                ('is_returned', models.BooleanField(blank=True, default=False, null=True, verbose_name='Qaytarildimi')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book', verbose_name='Kitob')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Xodimga berilgan kitob',
                'verbose_name_plural': 'Xodimga berilgan kitoblar',
                'ordering': ['employee'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        )
    ]
